### ISSUE TITLE
Missing Methods on Bitcoin::Protocol::Version ?

### ISSUE THREAD

**Issue by diclophis** [lian/bitcoin-ruby#12]
/Users/jbardin/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/bitcoin-ruby-0.0.1/lib/bitcoin/network/connection_handler.rb:257:in `addr': undefined method`services' for #Bitcoin::Protocol::Version:0x007f8a142fc1a0 (NoMethodError)

It looks like Bitcoin::Protocol::Version was updated to contain all the data in the :fields attribute?

**Comment by mhanne2** [comment]
@lian, I just sent you an email. Please could you add this account to bitcoin-ruby, I can't access my normal one.

**Comment by mhanne** [comment]
@mhanne2 nope, pretty sure I am me myself, and not you!

**Comment by mhanne2** [comment]
@lian, Clearly my account has been hacked. Check your email.

**Comment by lian** [comment]
bad luck, stop wasting our time. your mail is clearly fake.
