### ISSUE TITLE
Incorrect parsing of some non-P2SH scripts as P2SH

### ISSUE THREAD

**Issue by xHire** [lian/bitcoin-ruby#154]
I was playing with custom transactions (on testnet) and found that `bitcoin-ruby` thinks this script is P2SH:

    OP_DUP OP_HASH160 9cae7c65e5d7a2dcdf3e8fcbd8c91ead767806da OP_EQUALVERIFY OP_CHECKSIGVERIFY OP_HASH160 1b6246121883816fc0637e4aa280aca1df219b1a OP_EQUAL

While in fact the last hash is just a hash of a number at the bottom of the stack. For more details see transaction [156e6e1b84c5c3bd3a0927b25e4119fadce6e6d5186f363317511d1d680fae9a](http://blockexplorer.com/testnet/tx/156e6e1b84c5c3bd3a0927b25e4119fadce6e6d5186f363317511d1d680fae9a), that spends this script, and the input transaction that contains exactly the mentioned script in its output.

**Comment by mhanne** [comment]
Good catch! Thanks for reporting it, and for using testnet :)

**Comment by lian** [comment]
was fixed in https://github.com/lian/bitcoin-ruby/commit/bfa09b7258062a9f9e6da7e896718e30f56336a7
