### ISSUE TITLE
"Cannot load required dependency 'ffi-gtk3' - install with `gem install gir_ffi`"

### ISSUE THREAD

**Issue by omefire** [lian/bitcoin-ruby#155]
I get the following error when I try to run 'ruby -Ilib bin/bitcoin_gui' :

"Cannot load required dependency 'ffi-gtk3' - install with `gem install gir_ffi`"

I still get this error even after running: gem install gir_ffi.
How do I resolve this ? Thanks,

**Comment by mhanne** [comment]
Yes, there were some changes in how gir-ffi-gtk is loaded, and also some internal changes.
I just rebased my gui branch which fixes it:
https://github.com/mhanne/bitcoin-ruby/commits/gui

Note that the GUI is very experimental, so don't trust it with real money! It will also move to its own repository soon.

**Comment by lian** [comment]
@mhanne ok i removed the gui from base lib
