### ISSUE TITLE
Ruby 2.2 duplicated key warning in 0.0.6

### ISSUE THREAD

**Issue by sime** [lian/bitcoin-ruby#167]
The currently released version of bitcoin-ruby throws a warning in Ruby 2.2:

```
/home/staging/site/shared/bundle/ruby/2.2.0/gems/bitcoin-ruby-0.0.6/lib/bitcoin.rb:553: warning: duplicated key at line 564 ignored: :max_money
/home/staging/site/shared/bundle/ruby/2.2.0/gems/bitcoin-ruby-0.0.6/lib/bitcoin.rb:579: warning: duplicated key at line 590 ignored: :max_money
```

I can see that `bitcoin.rb` has changed considerably since then, but I would like suggest a 0.0.7 release to handle the noise.

Unfortunately I cannot see a 0.0.6 tag, we would need to be create it based off this commit: 0ebeee16539dcf74f336b2808bdda49c9fbf76e0

Following the tag, create abranch called "0.0.x" or "0.0" and resolve the duplicate keys in `bitcoin.rb` and tag 0.0.7.

**Comment by lian** [comment]
0.0.7 released

**Comment by sime** [comment]
Looks good. Thanks.
