### ISSUE TITLE
Can we get a 0.0.7 gem?

### ISSUE THREAD

**Issue by brighton36** [lian/bitcoin-ruby#169]
It's been about 6 months since the 0.0.6 release, and there are a number of bugfixes (for ruby 2.2) and features (Bitcoin.pubkey_to_address) that I'd like to include in my counterparty_ruby gem. 

If it would help, I'd be happy to submit a PR....

**Comment by lian** [comment]
yes, i will release 0.7 next week.

2015-05-28 16:50 GMT+02:00 Chris DeRose <notifications@github.com>:

**Comment by brighton36** [comment]
Thatks Wonderful - thank-you Lian!

**Comment by lian** [comment]
released. 0.0.8 will follow soon with some refactors though.

**Comment by brighton36** [comment]
Whoo-hoo! Thank-you.
