### ISSUE TITLE
How to generate compressed Bitcoin::Key?

### ISSUE THREAD

**Issue by MeLoco1** [lian/bitcoin-ruby#171]
The method produces uncompressed pub_key. 
I found some docs http://www.rubydoc.info/github/lian/bitcoin-ruby/Bitcoin/Key#generate-class_method
where compressed is default argument. 
However there is no such argument in the sources of the lib.

**Comment by lian** [comment]
https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin/key.rb#L12
