### ISSUE TITLE
Having issue with Bitcoin::P::Tx.from_json

### ISSUE THREAD

**Issue by njmurarka** [lian/bitcoin-ruby#172]
Hi.

I have been having alot of trouble trying to use this function as part of the process of creating and signing a new tx.

I tried to do the following:

prev_tx = Bitcoin::P::Tx.from_json(open("https://blockchain.info/rawtx/096cfd9c805b3d1c6881c988a0bbb73fd0ccf612205ec88909a9a4a24d27236d"))

And got back the following:

NoMethodError: undefined method `gsub' for 480990:Fixnum
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/txout.rb:69:in`from_hash'

I also tried the following instead:

prev_tx = Bitcoin::P::Tx.from_json(open("https://api.chain.com/v2/bitcoin/transactions/096cfd9c805b3d1c6881c988a0bbb73fd0ccf612205ec88909a9a4a24d27236d?api-key-id=DEMO-4a5e1e4"))

And got back the following:

prev_tx = Bitcoin::P::Tx.from_json(open("https://api.chain.com/v2/bitcoin/transactions/096cfd9c805b3d1c6881c988a0bbb73fd0ccf612205ec88909a9a4a24d27236d?api-key-id=DEMO-4a5e1e4"))
NoMethodError: undefined method `[]' for nil:NilClass
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/txin.rb:88:in`from_hash'
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/tx.rb:248:in `block in from_hash'
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/tx.rb:248:in`each'
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/tx.rb:248:in `from_hash'
    from /Users/loquitus/.rvm/gems/ruby-2.1.2/gems/bitcoin-ruby-0.0.7/lib/bitcoin/protocol/tx.rb:258:in`from_json'

Is there a specific service I can get tx hashes from that will work with the library? I am assuming each of these services (chain.com and blockchain.info) are returning varying formats that are both unexpected...

Thanks.

**Comment by njmurarka** [comment]
I think webbtc.com is down, or at least is at the time i am writing this. It would be nice if the library could work with the raw tx output of chain.com and blockchain.info.

**Comment by se3000** [comment]
Try using a [transaction hex endpoint](https://chain.com/docs#bitcoin-transaction-hex), it's a standardized format across APIs.

```
prev_tx = Bitcoin::Protocol::Tx.new.tap do |tx|
  tx.parse_data hex.htb
end
```

**Comment by mhanne** [comment]
Right, you should probably use the hex encoded tx data, because there is no official spec for the JSON format, and the hex version is shorter. If anything, the format bitcoin-ruby understands should be compatible with the one from blockexplorer.com - but IIRC we have some modifications to ensure en/decode roundtrips always work.

@se3000 why are you using #tap? Wouldn't just Tx.new(hex.htb) work as well?

And sorry about the webbtc downtime, the server had a hardware issue that is taken care of now.

**Comment by se3000** [comment]
@mhanne looks like it would. Bad habit.
