### ISSUE TITLE
Signing a transaction

### ISSUE THREAD

**Issue by rezozo** [lian/bitcoin-ruby#173]
I have generated a transaction object from a hex string using

``` ruby
parser = Bitcoin::Protocol::Parser.new()
tx = parser.process_pkt('tx', [body['txHex']].pack('H*'))
```

How can I sign it now? In bitcoinjs I would use

``` javascript
tx.sign(<input>, <key>)
```

EDIT: and if I'm generating it wrong, how can I generate a transaction object using a transaction that is hex-encoded?

**Comment by mhanne** [comment]
Signing a previously made transaction is a bit more involved (`Bitcoin::Builder` can sign transactions that were created with it, but can't import existing transactions).

Basically you need to:
- get the `signature_hash` for the given input you want to sign
- sign the hash with your key
- add the signature (and usually the pubkey) to the tx as the input script

Here is an example of how that might look:
https://github.com/lian/bitcoin-ruby/blob/master/examples/generate_tx.rb#L17

Btw. you can also use `Bitcoin::P::Tx.new(...)` directly, without going through the Parser.
