### ISSUE TITLE
create transaction

### ISSUE THREAD

**Issue by syrakozz** [lian/bitcoin-ruby#179]
is there any document or example to create a transaction between 2 btc

**Comment by mhanne** [comment]
Sure, see https://github.com/lian/bitcoin-ruby/blob/master/examples/generate_tx.rb if you want to get into the low-level details.

You can also use the `Bitcoin::Builder` to save yourself some trouble (http://bitcoin-ruby.org/Bitcoin/Builder/TxBuilder.html)
