### ISSUE TITLE
wrong number of argument 

### ISSUE THREAD

**Issue by syrakozz** [lian/bitcoin-ruby#180]
i am trying to create a key 

require 'rubygems'

require 'bitcoin'
require 'openssl'

require 'open-uri'

key = Bitcoin::generate_key

i got 

/usr/local/rvm/gems/ruby-1.9.3-p551/gems/bitcoin-ruby-0.0.8/lib/bitcoin.rb:191:in `initialize': wrong number of arguments(1 for 0) (ArgumentError)
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/bitcoin-ruby-0.0.8/lib/bitcoin.rb:191:in `new'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/bitcoin-ruby-0.0.8/lib/bitcoin.rb:191:in `bitcoin_elliptic_curve'
	from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/bitcoin-ruby-0.0.8/lib/bitcoin.rb:195:in `generate_key'
	from coin.rb:9:in `<main>'

**Comment by mhanne** [comment]
The code you pasted works for me, even though I'm not sure if ruby 1.9.3 is still supported...

You can try using `Bitcoin::Key.generate`, it's a wrapper around the same thing.

Can you post more about your setup, which exact revision you are running, etc.? (AFAIK 0.8.0 isn't on any
