### ISSUE TITLE
Fails self-test #20 on OSX 10.10 / ruby 2.1.5p273

### ISSUE THREAD

**Issue by rubyrailhead** [lian/bitcoin-ruby#183]
Test 20 fails:
% rake bacon
...
  20/21: spec/bitcoin/key_spec.rb                                 failed
Bitcoin::Key
  - should generate a key
  - should create empty key
  - should create key from priv + pub
  - should create key from only priv
  - should create key from only pub
  - should set public key
  - should set private key
  - should get addr
  - should sign data
  - should verify signature using public key
  - should verify signature using private key
  - recovers public keys from compact signatures
  - should export private key in base58 format
  - should import private key in base58 format
  - should export private key in compressed base58 format
  - should import private key in compressed base58 format
  - should handle compressed and uncompressed pubkeys
  - should handle private key in bip38 (non-ec-multiply) format [ERROR: LoadError]
  - should generate private key from warp format [ERROR: LoadError]

Bitcoin::OpenSSL_EC
  - resolves public from private key
  - recover public key from compact signature
  - sign and verify text messages

LoadError: cannot load such file -- scrypt
	/Users/ruby/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': Bitcoin::Key - should handle private key in bip38 (non-ec-multiply) format
	/Users/ruby/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Users/ruby/github/bitcoin-ruby/lib/bitcoin/key.rb:179:in `to_bip38'
	spec/bitcoin/key_spec.rb:217:in `block (2 levels) in <main>'
	spec/bitcoin/key_spec.rb:215:in `block in <main>'
	spec/bitcoin/key_spec.rb:5:in `<main>'

LoadError: cannot load such file -- scrypt
	/Users/ruby/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': Bitcoin::Key - should generate private key from warp format
	/Users/ruby/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Users/ruby/github/bitcoin-ruby/lib/bitcoin/key.rb:235:in `from_warp'
	spec/bitcoin/key_spec.rb:242:in `block (2 levels) in <main>'
	spec/bitcoin/key_spec.rb:241:in `block in <main>'
	spec/bitcoin/key_spec.rb:5:in `<main>'

22 specifications (208 requirements), 0 failures, 2 errors
Coverage report generated for RSpec to /Users/ruby/github/bitcoin-ruby/coverage. 929 / 1862 LOC (49.89%) covered.

**Comment by mhanne** [comment]
Hi,
you're just missing the `scrypt` dependency, running `bundle install` should get you everything needed.
In case you don't have `bundle`, do `gem install bundler` first.
