### ISSUE TITLE
OpenSSL_EC.signature_to_low_s produces negative S value

### ISSUE THREAD

**Issue by chinh7** [lian/bitcoin-ruby#185]
I've been using v0.0.5 to create new transaction but recently it has started creating transactions with high S value. I upgraded to v0.0.7 but it is somehow producing transactions with invalid input signature (Script returns non-true). I'm trying to figure out why but in the mean time my solution is to keep using v0.0.5 and manually convert high S to low S using OpenSSL_EC.signature_to_low_s. It worked fine until my latest attempt. The conversion was successful, however the converted S value became negative:

``` ruby
hash = {"prev_out"=>{"hash"=>"81ae425121bc2a367ce18476a2148bc0d062cefb8e30880843bd98b3584a1e2a", "n"=>19}, "scriptSig"=>"304502207321323a6dc995dbb84e765214918953ca9491fbff6f4d8f36f7090186a1638a022100ff1d03f1ace5045d27d8daa7f073e4282238094f595058cc7293da434cb3648601 023d3e2ed0853e318cc9807836a99136242fcac4874d54b44dc8f366e5509eee72"}
tx_in = Bitcoin::P::TxIn.from_hash hash
script_sig = Bitcoin::Script.new(tx_in.script_sig)
sig = script_sig.chunks[0]
pubkey = script_sig.chunks[1]
Bitcoin::Script::is_der_signature?(sig) #true
Bitcoin::Script::is_low_der_signature?(sig) #false
sig = Bitcoin::OpenSSL_EC.signature_to_low_s(sig)
tx_in.script_sig = Bitcoin::Script.to_signature_pubkey_script(sig, pubkey)
Bitcoin::Script::is_low_der_signature?(sig) #true
Bitcoin::Script::is_der_signature?(sig) #false
```

Any recommendation on how to convert this high S value without making the signature non-der? Thanks

**Comment by lian** [comment]
fixed in d7ac93635ad546bb2ae86a09b41ee6e0405d515c
