### ISSUE TITLE
How do we create previous transaction? Can anyone tell me?

### ISSUE THREAD

**Issue by yuuki1224** [lian/bitcoin-ruby#186]
I've just started to use this gem and read [this section](https://github.com/lian/bitcoin-ruby#create-transactions) on `README.md`. But I've got little confusion in creating new transaction...
I understand that the input of previous transaction should be all of bitcoin which I previously have received and the output of previous transaction should be the difference of the amount of input and the amount which I want to spent to other address from now. But how do I create the this previous transaction? Can anyone help me?(I want to see what the code looks like)

※ If this question is not prefer here, sorry for that and I can move to prefer place.

**Comment by alexishida** [comment]
I have been used https://testnet.blockexplorer.com/api/addr/miDjtnz67hHy5fdNBJ2XjoBCXGimdSfeT6
and i get the last transaction in this case 955bcf1d06ed1c33472da35062443d12f7f5035f981841d271e394cca0eced51 and get txid using https://testnet.blockexplorer.com/api/tx/955bcf1d06ed1c33472da35062443d12f7f5035f981841d271e394cca0eced51

But whe I try make json parse using prev_tx = Bitcoin::P::Tx.from_json(open("https://testnet.blockexplorer.com/api/tx/#{prev_hash}"))

this error appear
/usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bitcoin-ruby-0.0.10/lib/bitcoin/protocol/tx.rb:261:in `from_hash': undefined method `each' for nil:NilClass (NoMethodError)
	from /usr/local/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bitcoin-ruby-0.0.10/lib/bitcoin/protocol/tx.rb:274:in `from_json'
	from app.rb:30:in `prev_tx'
	from app.rb:52:in `<main>'

**Comment by iSunRise** [comment]
@yuuki1224 you have to generate bitcoin address in testnet mode. Then you can use faucets to receive some bitcoins into your test wallet (and create the first transaction which you need).
Don't forget to send BTC back so other developers will be able to use these coins.
[Here you can find one of the faucets](https://testnet.coinfaucet.eu/en/)

**Comment by glaksmono** [comment]
@iSunRise what is the URL that you use for the `prev_tx`, I'm getting this:

```
2.4.2 :013 > prev_tx = Bitcoin::P::Tx.from_json(open("http://test.webbtc.com/tx/#{prev_hash}.json"))
Errno::ENOENT: No such file or directory @ rb_sysopen - http://test.webbtc.com/tx/c9fd744f87362b27113080ed2ca7b08cd5eb0652b3a52afad9408f647431cdc9.json
	from (irb):13:in `initialize'
	from (irb):13:in `open'
	from (irb):13
```

I've also tried this:

```
2.4.2 :015 > prev_tx = Bitcoin::P::Tx.from_json(open("https://api.blockcypher.com/v1/btc/test3/txs/#{prev_hash}"))
Errno::ENOENT: No such file or directory @ rb_sysopen - https://api.blockcypher.com/v1/btc/test3/txs/c9fd744f87362b27113080ed2ca7b08cd5eb0652b3a52afad9408f647431cdc9
	from (irb):15:in `initialize'
	from (irb):15:in `open'
	from (irb):15
```

**Comment by lian** [comment]
from_json will be deprecated. fetch the binary or hex of the transaction and call `Tx.new(binary)` instead.
