### ISSUE TITLE
Issue with OP_RETURN encoding?

### ISSUE THREAD

**Issue by redsquirrel** [lian/bitcoin-ruby#191]
I've built a transaction and sent it out, but it seems like something isn't working quite right.

```ruby
build_tx do |t|
  # snipped other stuff
  t.output {|o| o.to "@redsquirrel", :op_return }
end
```

Here's the transaction: https://blockchain.info/tx/18dbf777b678fa5e1ce8a48c0c94a980f09ba6de3970e7cf5b0afa951e2af4d9

Am I doing something wrong? How do I get `@redsquirrel` out?

**Comment by redsquirrel** [comment]
All the examples and specs use `"deadbeef"` as the `op_return` data, and this obviously works. It just dawned on me that all of these letters are valid hex characters. Are we supposed to encode this data before we pass it into `TxOutBuilder#to`?

**Comment by redsquirrel** [comment]
Closing this out because (I think) I figured it out. :smile: 

```ruby
build_tx do |t|
  # snipped other stuff
  t.output {|o| o.to "@redsquirrel".unpack("H*")[0], :op_return }
end
```

Here's the transaction: https://blockchain.info/tx/a5f7a7fc760f159411e9797321a7c9842d964c218dd2f5261d4c5bd59ce705c3

**Comment by mhanne** [comment]
Right, the data is expected in hex encoding - the example doesn't quite make it obvious, I admit that ;)

Btw. in case anyone else was wondering: the "j" shown by blockchain.info the encoded OP_RETURN opcode.
