### ISSUE TITLE
How to get tx input amount?

### ISSUE THREAD

**Issue by JokerCatz** [lian/bitcoin-ruby#194]
Hi , all , first sorry my poor English

I need a method to decode hex from bitcoin core gettransaction["hex"]

here is my code

    require 'bitcoin'
    require 'pp'
    
    print "input hex : "
    
    hex_bin = gets.strip.scan(/../).map{|x|x.hex.chr}.join
    
    tx = Bitcoin::Protocol::Tx.new(hex_bin)
    
    ans = {:receive => [] , :send => [] , :receive_total => 0 , :send_total => 0 , :fees => nil}
    tx.in.each do |tx_in|
      ans[:send] << {:txid => tx_in.previous_output , :vout => tx_in.prev_out_index}
    end
    tx.out.each do |tx_out|
      ans[:receive] << {:addr => tx_out.parsed_script.get_address , :amount => tx_out.value}
      ans[:receive_total] += tx_out.value
    end
    
    pp ans

It's work very well , but how to get tx_in amount? , and tx_out[:vout] is index of tx.out right ?

**Comment by mhanne** [comment]
Hi,

the binary transaction format doesn't include the input amount, only a reference to the previous output. You'll have to look up the `tx_in.previous_output` tx and check the output number `tx_in.prev_out_index`.
So yes, what you call `vout` is the index of the corresponding output in the previous transaction.

**Comment by JokerCatz** [comment]
okay , may thanx : )
