### ISSUE TITLE
Transaction generated by bitcoin ruby rejected by network

### ISSUE THREAD

**Issue by phuongnd08** [lian/bitcoin-ruby#195]
I received some bitcoin to my address at this:
https://blockchain.info/tx/8dfc984e1f6717568339289f32fea5d11af4553b09ac171fb6be76d92c3a4258
When I use the input and sign with Bitcoin ruby, I get this raw hex:

010000000158423a2cd976beb61f17ac093b55f41ad1a5fe329f2839835617671f4e98fc8d010000006c493046022100eb406b2227e2f90d6306057de8e7d8d06411c5a8e9ab4d1f1b981b8d765b3cb9022100f7dbabb9378841938f91f8216447878e04ce034625c0ab3147c64b656c3f2b0c012103cc9756fb311905dbf64e67eb18b442a16d6fab9b88a0a7b4a8acdcdfc772f8e8ffffffff01f09aeb0b000000001976a9143c52da4634d48711f2b41d7b2b55a836f4b2f57888ac00000000

Attempt to push this to https://blockchain.info/pushtx result in this:
`Non-canonical signature: High S Value`

Anyone has a clue why is that? We have successful relayed hundred of other transactions using bitcoin-ruby without fail, but here come this.

**Comment by phuongnd08** [comment]
This is suggesting a fix related to s, r value: https://bitcointalk.org/index.php?topic=1356430.0

**Comment by phuongnd08** [comment]
@lian would you mind have some input on this? I think this should be an easy fix for you?

**Comment by mhanne** [comment]
Hi, sorry if I'm missing something, but on first glance it looks like this is what `Script.is_low_der_signature?` is checking. Maybe you just need to enable the `:verify_low_s` option?

**Comment by mhanne** [comment]
Ah, but there is `Bitcoin::OpenSSL_EC.signature_to_low_s(sig)`. So you can use `Script.is_low_der_signature?` to check the signature and fix it if need be.
See `spec/bitcoin/ffi_openssl.rb`.

**Comment by mhanne** [comment]
Also, `Bitcoin.sign_data` is doing that already.

**Comment by mhanne** [comment]
@phuongnd08 how exactly are you signing your txs? Could you create a test case that triggers the error?
Seems to me like all common ways to sign should go through `Bitcoin.sign_data` (for example if you use Bitcoin::Key).

**Comment by nbphuoc** [comment]
@mhanne We were using version 0.0.6 to sign the transactions, after upgrading to 0.0.7 everything work fine. Thank you.
