### ISSUE TITLE
bitcoin-ruby support segwit?

### ISSUE THREAD

**Issue by azuchi** [lian/bitcoin-ruby#198]
Bitcoin Core 0.13.0 has been released, and segwit is now available in the testnet.

So bitcoin-ruby has plan to support segwit?

**Comment by lian** [comment]
noticed the branch in your fork. looking forward to it :)

**Comment by azuchi** [comment]
It can now parse and build segwit transaction, and calculate SIGHASH. I'm working on segwit signature creation and verification.

But the problem is whether Segwit will be activated or not on mainnet.

**Comment by azuchi** [comment]
I created a pull request for segwit (#203), so I close this Issue.
