### ISSUE TITLE
Generate Compressed and Uncompressed Address From Private Key (WIF)

### ISSUE THREAD

**Issue by acegilz** [lian/bitcoin-ruby#199]
It seems to be pretty simple but the truth is that I'm struggling to do this for the last 2 days.
Google is also not helping me today

**Comment by lian** [comment]
https://en.bitcoin.it/wiki/Wallet_import_format

`Bitcoin::Key.from_base58("5HueCGU8rMjxEXxiPuD5BDku4MkFqeZyd4dZ1jvhTVqvbTLvyTJ")`

https://github.com/lian/bitcoin-ruby/blob/master/spec/bitcoin/key_spec.rb#L143

**Comment by acegilz** [comment]
@lian this returns the uncompressed address, but how can I get both as requested on tittle.

**Comment by lian** [comment]
`key.pub_compressed` and `key.pub_uncompressed` but this doesn't make sense. the WIF format already handles if this key is supposed to be compressed or uncompressed. https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin/key.rb#L22

**Comment by lian** [comment]
you could also do ugly `key.instance_eval{ @pubkey_compressed = false|true }; key.addr`
