### ISSUE TITLE
Deprecated openssl calls during initialization

### ISSUE THREAD

**Issue by jimpo** [lian/bitcoin-ruby#205]
`FFI::NotFoundError: Function 'SSL_library_init' not found in [libssl.so]`

`SSL_library_init` was deprecated in OpenSSL 1.1.0 along with ERR_load_crypto_strings, and SSL_load_error_strings. They are called from https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin/ffi/openssl.rb#L379.

https://www.openssl.org/docs/man1.1.0/ssl/SSL_library_init.html
https://www.openssl.org/docs/man1.1.0/crypto/ERR_load_crypto_strings.html
https://www.openssl.org/docs/man1.1.0/crypto/SSL_load_error_strings.html

**Comment by michalf** [comment]
Hi, is this a permanent fix? It definitely works for us, but it would be great if it was included in a published gem. Otherwise managing gems gets a bit more difficult (`specific_install` to the rescue).

Thanks for your great work!

**Comment by lian** [comment]
yes, will release a new gem this week. merging segwit support too. :)
