### ISSUE TITLE
Change http://test.webbtc.com api to https://blockexplorer.com/api/

### ISSUE THREAD

**Issue by alexishida** [lian/bitcoin-ruby#209]
Sugestion:
Change http://test.webbtc.com api to https://blockexplorer.com/api/ in readme example!

**Comment by alexishida** [comment]
Sorry the correct link for testnet3 is:

https://testnet.blockexplorer.com/api

and the livenet is 

https://blockexplorer.com/api

**Comment by lian** [comment]
need to get rid of all to/from_json examples since there is no block explorer that outputs the needed json format anymore. will keep the methods though since it works fine if you use to/from_json internally yourself.
