### ISSUE TITLE
RangeError : load block data from Bitcoin testnet (1151351)

### ISSUE THREAD

**Issue by JokerCatz** [lian/bitcoin-ruby#210]
RangeError( bignum too big to convert into `long' )
    lib/bitcoin/protocol/txin.rb:70:in `read'
    
    from Bitcoin testnet block (1151351)

block data load from bitcoin core

    block_data = `bitcoin-cli getblock $(bitcoin-cli getblockhash 1151351) false`
    block = Bitcoin::Protocol::Block.new(Array(block_data).pack('H*'))

tested Ruby 2.3.2 & 2.4.1

    bug ...
    @script_sig_length = 13949216059600273407

**Comment by JokerCatz** [comment]
@azuchi thanx , it worked and fixed , the bug same in :litecoin , many thanx : )

**Comment by JokerCatz** [comment]
Hi , I try to sign to transaction , but I get some error ... it same error from segwit support?

    require 'bitcoin'
    require 'base64'
    require 'zlib'
    
    include Bitcoin::Builder
    Bitcoin.network = :testnet3
    
    #txid : 3a3e6199d2e921fd041368639d215f4d50c13224bf41998fb5b7adae7dadff96
    prev_trans = "eJxtU0mSHDEI/BKLWPQcQPD/J5iesU9t6qAIhZTKrYDgd8jIyY5QHw97jmf4vTigUqrs5xyX/YAj5ao/VyOS5xTnUYoB/gJpHmc4AkS7U/Kq6QJdQrGLV9KSMfEpDSzGHnkD9wlOVIvcUsEHIiVh8BYFLCx7ITVaAUPV+p6JZJNORwjKZ60ZyD44L4qmGjIceWJ54TL5aEPVQ3NOvRWCM+9e3CUnkCC1Ad2x+capqKPNfuFhFEv5nZ6fMeZBtDulJhxcqBKFKzNjRqwl5ZkPQ4MLTfMSOwDhJkoH/+/T6NPDNoy3fE5NHr3kieGfR8VTNpe7ChqK2k0v3PZIGz8K8ePTQy2RNqw0lJBENnrei6I9SzX6oVDoRptr/1qJ2HmzNmX/6xM/X2dLH9+Orq2BnhMItS6FnDenc59yfVl3lIVurWw83Lvn/s8nkNh8/6n9DF7TlXBSn8nNLVZOInH2tDBzTYetvpfcJz3cNwXYDvA3BubUMoUDFGgW6VtTX16hZrwZ61Edqg9Gw12jvzGeBG/SK/PWFWzSTPe62xsoxdmCs7T4B+OVEuU3RrWtFzxEu+4d9KFHDlv6lzJ3OxDmTR8M3/KCfmNw+eHcH+Munb14QF7LhrodPgMvwnDDvh+M7SzievoH+3v7kQ=="
    prev_trans = Zlib.inflate(Base64.decode64(prev_trans))
    
    prev_tx = Bitcoin::P::Tx.new([prev_trans].pack('H*'))
    prev_hash = prev_tx.hash
    prev_out_index = 0
    
    #vout(0) wallet = "mxBjFn5LE9Dk3yyRS7JE3W6fL5fK3CfiiY"
    #vout(0) pkey   = "cR2LajwWFsSKzn2TJWGR1iNMFC5AVqvWPhEdMz1bg92QUZpE6djK"
    
    key = Bitcoin::Key.from_base58("cR2LajwWFsSKzn2TJWGR1iNMFC5AVqvWPhEdMz1bg92QUZpE6djK")
    
    new_tx = build_tx do |t|
      t.input do |i|
        i.prev_out prev_tx
        i.prev_out_index prev_out_index
        i.signature_key key
     end
    
      t.output do |o|
        o.value 10000 # 0.0001 BTC
        o.script do |s|
          s.recipient "mxBjFn5LE9Dk3yyRS7JE3W6fL5fK3CfiiY" #self to self
        end
      end
    end

    #RuntimeError: pubkey is not in binary form

    puts new_tx.to_json

I tried

    lian/bitcoin-ruby(master)
    ## lib/bitcoin/builder.rb:280:in `sign_input': Signature error (RuntimeError)

    azuchi/bitcoin-ruby(segwit_tx_support)
    ## lib/bitcoin/script.rb:806:in `to_pubkey_script_sig': pubkey is not in binary form (RuntimeError)

is I make something mistake??

**Comment by azuchi** [comment]
@JokerCatz It is a mistake in specifying `prev_out`. `prev_out` specify previous tx hash.

so 

```
i.prev_out prev_hash
```

is correct.

**Comment by JokerCatz** [comment]
okay I got and sign success ... thanx , it typo ... sorry for it |||

**Comment by JokerCatz** [comment]
@azuchi  I double confirm my demo code , it same code as README [Create Transactions]

the `prev_tx` is Tx obj not string txid , it need to verify scriptPubKey / redeemScript to sendrawtransaction ... if use txid not obj , when use `bitcoin-cli sendrawtransaction` will get error : 

    error code: -26
    error message:
    16: mandatory-script-verify-flag-failed (Operation not valid with the current stack size)

and decoderawtransaction the vin["scriptSig"]["asm"] & vin["scriptSig"]["hex"] will be empty...

**Comment by azuchi** [comment]
@JokerCatz Sorry, I misunderstood.

maybe private key is invalid.

tx `3a3e6199d2e921fd041368639d215f4d50c13224bf41998fb5b7adae7dadff96 ` [0]'s script pubkey is 

```
"scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 b6d759b65cbfb123befe5333cfea76e0db3e4b8a OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914b6d759b65cbfb123befe5333cfea76e0db3e4b8a88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mxBjFn5LE9Dk3yyRS7JE3W6fL5fK3CfiiY"
        ]
      }
```

it's pubkeyhash is `b6d759b65cbfb123befe5333cfea76e0db3e4b8a`.

but above private key's pubkeyhash dose not match it.

```
key = Bitcoin::Key.from_base58("cR2LajwWFsSKzn2TJWGR1iNMFC5AVqvWPhEdMz1bg92QUZpE6djK")
key.hash160
=> 1c0614455dfbd1a0d8100ff1b63ee4f31d69781c
key.addr
=> mi58VpBi2s4SbdM9iZR4cEHmxVLHVRhk2T
```

**Comment by JokerCatz** [comment]
okay ... I find a big issue , it same code and different ans from ruby version 2.2.6 & 2.4.1 , I add another issue to report it ...
