### ISSUE TITLE
ruby 2.4.1 priv & pub key is not match ...

### ISSUE THREAD

**Issue by JokerCatz** [lian/bitcoin-ruby#211]
I use a clean computer (ubuntu 16.04) install rvm & install ruby 2.2.6 & 2.4.1 , use

    rvm install 2.2.6
    rvm use 2.2.6
    gem i ffi
    gem i bitcoin-ruby

    rvm install 2.4.1
    rvm use 2.4.1
    gem i ffi
    gem i bitcoin-ruby

[[main.rb]]

    require 'bitcoin'
    include Bitcoin::Builder
    Bitcoin.network = :testnet3
    key = Bitcoin::Key.from_base58("cR2LajwWFsSKzn2TJWGR1iNMFC5AVqvWPhEdMz1bg92QUZpE6djK")
    puts key.hash160
    puts key.addr

[[test]]

    rvm use 2.2.6
    ruby main.rb
    #=> 1c0614455dfbd1a0d8100ff1b63ee4f31d69781c
    #=> mi58VpBi2s4SbdM9iZR4cEHmxVLHVRhk2T

    rvm use 2.4.1
    ruby main.rb
    #=> b6d759b65cbfb123befe5333cfea76e0db3e4b8a
    #=> mxBjFn5LE9Dk3yyRS7JE3W6fL5fK3CfiiY
    
... I think this is very important for lost private keys ... & 2.2.6 is right ans , source key is generate from this gem , I think this is very important to lost public / private key match ......

**Comment by azuchi** [comment]
This is due to changes in openssl's behavior in ruby 2.4.x.
And this issue is fixed by #208 .

Currently gem is not yet compatible version, so if you want to use ruby 2.4.x you need to build gem.

**Comment by JokerCatz** [comment]
okay , thinx ..... , I'll take care of this

**Comment by lian** [comment]
@azuchi 👍 

@JokerCatz i will release a new gem version this week
