### ISSUE TITLE
Clarification question

### ISSUE THREAD

**Issue by uneeb123** [lian/bitcoin-ruby#253]
https://github.com/lian/bitcoin-ruby/blob/a3fffe07505ea8e0c11dac548ae0dda0f8168f12/lib/bitcoin/connection.rb#L69

What is the block number supposed to represent here?

**Comment by lian** [comment]
https://en.bitcoin.it/wiki/Protocol_documentation#version

`start_height` - `The last block received by the emitting node`

https://github.com/lian/bitcoin-ruby/blob/a3fffe07505ea8e0c11dac548ae0dda0f8168f12/lib/bitcoin/protocol/version.rb
