### ISSUE TITLE
How do you get "the key needed to sign an input that spends the previous output"?

### ISSUE THREAD

**Issue by glaksmono** [lian/bitcoin-ruby#258]
I don't really understand this part, can someone help me out here?

```
# the key needed to sign an input that spends the previous output
key = Bitcoin::Key.from_base58("92ZRu28m2GHSKaaF2W7RswJ2iJYpTzVhBaN6ZLs7TENCs4b7ML8")
```

**Comment by kento1218** [comment]
First of all, you have to generate your private key at your end first and generate an address from the key, then send (deposit) some money to the address  from somewhere (another wallet you have, some exchange, or whatever).
After that, you can spend previous given money (txout) to send to somewhere else.

You may mentioned about instructions on [README](https://github.com/lian/bitcoin-ruby#create-transactions). Those instructions assume that, you already have private key `92ZRu28m...` and incoming tx `6c44b284...`, and show how to spent that txout.
