### ISSUE TITLE
undefined method `dsa_sign_asn1'

### ISSUE THREAD

**Issue by deflexor** [lian/bitcoin-ruby#317]
Hi, geeting this error when try to create transaction as in examples/[generate_tx.rb](https://github.com/lian/bitcoin-ruby/blob/master/examples/generate_tx.rb)

```Undefined method `dsa_sign_asn1' for #<Bitcoin::Key:0x000055b91864c888>
Backtrace:  
.../versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/bitcoin-ruby-f9b817c946b3/lib/bitcoin.rb:379:in `block in sign_data'
```

**Comment by azuchi** [comment]
`dsa_sign_asn1` is a method of `OpenSSL::PKey::EC`. The error seems to be calling `dsa_sign_asn1` for `Bitcoin::Key`.

In the sample, the

```ruby
key = Bitcoin.open_key("9b2f08ebc186d435ffc1d10f3627f05ce4b983b72c76b0aee4fcce99e57b0342")
```

with `Bitcoin.sign_data` as the argument. This `key` is `OpenSSL::PKey::EC`. Are you accidentally passing `Bitcoin::Key`?

**Comment by deflexor** [comment]
I passing key this way:
```
key = Bitcoin::Key.generate
// save key to file
save_string_to_file(key.to_base58)
recovered_key = Bitcoin::Key.from_base58(read_string_from_file)
```
So this `recovered_key` is what i'm passing.

**Comment by azuchi** [comment]
`Bitcoin::Key.from_base58` returns `Bitcoin::Key` itself, so you need to use `recovered_key.sing(data)` instead of `Bitcoin.sign_data(recovered_key, data)`.

**Comment by deflexor** [comment]
Oh, thank you, that worked.
