### ISSUE TITLE
Trying to support dogecoin

### ISSUE THREAD

**Issue by indirect** [lian/bitcoin-ruby#49]
I'm trying to re-use the litecoin support to add support for dogecoin, but I can't figure out where in the dogecoin codebase to look for these magic constants:

```
      :magic_head => "\xfb\xc0\xb6\xdb",
      :address_version => "30",
      :p2sh_version => "05",
      :privkey_version => "b0",
```

I found all the rest of them :P Fucking cryptocurrency, how does it work?

**Comment by mhanne** [comment]
Well, it looks like we support dogecoin now
https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin.rb#L697
https://github.com/lian/bitcoin-ruby/blob/master/lib/bitcoin/dogecoin.rb

If there are any problems, please open a new issue.
