### ISSUE TITLE
Some operations are blocked when storing blocks

### ISSUE THREAD

**Issue by isaacwaldron** [lian/bitcoin-ruby#70]
I run a sequel::postgres node and it appears that some operations are blocked when the storage backend is validating and storing a block.  With verbose output set I see lots of lines like:

    DEBUG storage: validating tx context 817e1e2b6a26f87620a5247a4146c39dd170364b636ae49c46425615ae4d32d8 (6369 bytes)

During this time postgresql is consuming 100% CPU and some operations hang for a long time.  For example, running bin/bitcoin_node info will not return until the block has been stored and new CommandClient instances cannot subscribe to notification channels.  It doesn't look like the main EM loop is blocked though because Ctrl-C still puts the node into shutdown mode.

**Comment by mhanne** [comment]
https://github.com/mhanne/bitcoin-ruby-blockchain/issues/8
